# ----------------------------
# MongoDB Atlas connection string
# ----------------------------
MONGO_URI = "mongodb+srv://Ayushman:rahul1510@feedbackapp.p8r8atm.mongodb.net/feedbackdb?retryWrites=true&w=majority&appName=FeedbackApp"


# ----------------------------
# Admin password for the app
# ----------------------------
ADMIN_PASSWORD = "Kpmg@2025"
